//1

// function divide(a, b) {
//     if (b === 0) {
//         return "Деление на ноль невозможно";
//     } else {
//         return a / b;
//     }
// }
// console.log(divide(10, 2));


//2

// function square(num) {
//     return num * num;
// }
// console.log(square(5));


//3

// function sumArray(arr) {
//     let sum = 0;
//     for (let i = 0; i < arr.length; i++) {
//     sum += arr[i];
//     }
//     return sum;
// }
// console.log(sumArray([1, 2, 3, 4]));


//4

// function stringLength(str) {
//     return str.length;
// }
// console.log(stringLength("Hello"));


//5

// function absoluteValue(num) {
//     return Math.abs(num);
// }
// console.log(absoluteValue(-5));


//6

// function stringLengths(arr) {
//     return arr.map(str => str.length);
// }
// console.log(stringLengths(["apple", "banana", "cherry"])); 


//7

// function max(a, b) {
//     return Math.max(a, b);
// }
// console.log(max(5, 8));


//8

// function repeatString(str, count) {
//     return str.repeat(count);
// }
// console.log(repeatString("ha", 24));


//9

// function doubleArray(arr) {
//     return arr.map(num => num * 2);
// }
// console.log(doubleArray([1, 2, 3]));


//10

// function isEven(num) {
//     return num % 2 === 0;
// }
// console.log(isEven(4));
// console.log(isEven(5));